# Python venvs that live OUTSIDE the source tree, entered via direnv.
#
# Problem:
#   Every repo used to carry its own venv (.venv, .mlis-py3.13, ...) plus an
#   .envrc of `source .venv/bin/activate`. That path is RELATIVE to the .envrc,
#   so a `git worktree` of the same repo has no venv (or a dangling .envrc), a
#   checkout cannot be thrown away without losing its venv, and the venv name
#   said nothing true about its python (.mlis-py3.13 was actually 3.12).
#
# Solution:
#   One directory, $PY_VENVS (~/tmp/pyvenvs), holds every venv, named
#   py-<X.Y>_<dirname> (e.g. py-3.12_ezaddon-mlis -- that name is what PS1
#   shows, see prompt.bashrc.sh). An .envrc records only the venv NAME and
#   resolves it through $PY_VENVS, so it works from any checkout or worktree
#   and no repo hardcodes a filesystem path:
#
#       : "${PY_VENVS:?...}"
#       source "$PY_VENVS/py-3.12_ezaddon-mlis/bin/activate"
#
#   Per-workstream venvs (juggler's ~/.config/juggler/seed/ezaddon-mlis/.envrc)
#   follow the same scheme with the ticket appended: py-3.12_ezaddon-mlis-AISW-NNNNN.
#
# UX:
#   pyvenv-create [-p PYTHON] [-f] [NAME]  new venv for the cwd, write .envrc, direnv allow
#   pyvenv-use    [-f] NAME                .envrc -> an EXISTING venv (the worktree case)
#   pyvenv-adopt  [-f] [NAME] [VENV_DIR]   move an in-repo venv into $PY_VENVS, fix the
#                                          paths it has baked in, write .envrc
#   pyvenv-ls                              what is in $PY_VENVS
#
#   NAME defaults to py-<X.Y>_$(basename "$PWD"). An existing .envrc is only
#   overwritten if it contains nothing but venv activation; -f forces it.

# A plain assignment on purpose (not ${PY_VENVS:=...}): re-sourcing ~/.bashrc
# must be enough to fix a shell that is holding an old value.
export PY_VENVS="$HOME/tmp/pyvenvs"

# X.Y of an interpreter.
_pyvenv_pyver() {
    "$1" -c 'import sys; print("%d.%d" % sys.version_info[:2])' 2>/dev/null
}

# py-<X.Y>_<basename of cwd>
_pyvenv_default_name() {
    printf 'py-%s_%s' "$1" "$(basename "$PWD")"
}

# A venv name is a plain directory name, nothing else.
_pyvenv_check_name() {
    case "$1" in
        ''|.|..|*/*|-*)
            echo "pyvenv: bad venv name '$1' (want a plain name like py-3.12_myrepo)" >&2
            return 1;;
    esac
}

# True if ./.envrc is absent or contains nothing but venv activation (ours, or
# the old `source .venv/bin/activate` kind). Anything else (dotenv, PATH_add,
# exports...) is real config of somebody's: refuse to clobber it unless forced.
_pyvenv_envrc_replaceable() {
    [ -e .envrc ] || return 0
    local line
    while IFS= read -r line || [ -n "$line" ]; do
        line="${line#"${line%%[![:space:]]*}"}"   # ltrim
        line="${line%"${line##*[![:space:]]}"}"   # rtrim
        case "$line" in
            ''|'#'*) ;;
            'source '*'/bin/activate'|'source '*'/bin/activate"'|'. '*'/bin/activate'|'. '*'/bin/activate"') ;;
            ': "${PY_VENVS:?'*) ;;
            *) return 1;;
        esac
    done < .envrc
    return 0
}

# Write ./.envrc pointing at $PY_VENVS/NAME and `direnv allow` it.
_pyvenv_write_envrc() {  # NAME FORCE(0|1)
    local name="$1" force="$2"
    if [ "$force" != 1 ] && ! _pyvenv_envrc_replaceable; then
        echo "pyvenv: $PWD/.envrc has more than venv activation in it; re-run with -f to overwrite" >&2
        return 1
    fi
    cat > .envrc <<EOF
# Generated by pyvenv (linux_config/bashrcs/pyvenv.bashrc.sh).
# The venv lives OUTSIDE this checkout, in \$PY_VENVS, so worktrees can share it.
: "\${PY_VENVS:?PY_VENVS is not set -- source linux_config/bashrcs/pyvenv.bashrc.sh}"
source "\$PY_VENVS/${name}/bin/activate"
EOF
    echo "pyvenv: $PWD/.envrc -> \$PY_VENVS/${name}"
    if command -v direnv >/dev/null 2>&1; then
        direnv allow "$PWD/.envrc"
    fi
}

# Escape for the pattern / replacement side of sed s|..|..|.
_pyvenv_sed_pat() { printf '%s' "$1" | sed 's/[.[\*^$|\\]/\\&/g'; }
_pyvenv_sed_rep() { printf '%s' "$1" | sed 's/[&|\\]/\\&/g'; }

pyvenv-create() {
    local usage='usage: pyvenv-create [-p PYTHON] [-f] [NAME]'
    local py=python3 force=0 OPTIND opt
    while getopts ':p:fh' opt; do
        case "$opt" in
            p) py="$OPTARG";;
            f) force=1;;
            h) echo "$usage"; return 0;;
            *) echo "$usage" >&2; return 2;;
        esac
    done
    shift $((OPTIND - 1))

    local ver name dir
    ver="$(_pyvenv_pyver "$py")" || { echo "pyvenv-create: cannot run '$py'" >&2; return 1; }
    name="${1:-$(_pyvenv_default_name "$ver")}"
    _pyvenv_check_name "$name" || return 1
    dir="$PY_VENVS/$name"
    if [ -e "$dir" ]; then
        echo "pyvenv-create: $dir already exists; \`pyvenv-use $name\` points this dir at it" >&2
        return 1
    fi
    # Check .envrc BEFORE creating anything so a refusal leaves nothing behind.
    if [ "$force" != 1 ] && ! _pyvenv_envrc_replaceable; then
        echo "pyvenv-create: $PWD/.envrc has more than venv activation in it; re-run with -f" >&2
        return 1
    fi

    mkdir -p "$PY_VENVS" || return 1
    echo "pyvenv-create: $py -m venv $dir"
    "$py" -m venv "$dir" || return 1
    _pyvenv_write_envrc "$name" 1 || return 1
    echo "pyvenv-create: direnv loads it at the next prompt"
    if [ -f requirements.txt ] || [ -f pyproject.toml ]; then
        echo "pyvenv-create: hint: then pip install -r requirements.txt / pip install -e ."
    fi
}

pyvenv-use() {
    local usage='usage: pyvenv-use [-f] NAME    (names: pyvenv-ls)'
    local force=0 OPTIND opt
    while getopts ':fh' opt; do
        case "$opt" in
            f) force=1;;
            h) echo "$usage"; return 0;;
            *) echo "$usage" >&2; return 2;;
        esac
    done
    shift $((OPTIND - 1))

    local name="$1"
    [ -n "$name" ] || { echo "$usage" >&2; return 2; }
    _pyvenv_check_name "$name" || return 1
    if [ ! -f "$PY_VENVS/$name/bin/activate" ]; then
        echo "pyvenv-use: no venv at $PY_VENVS/$name (names: pyvenv-ls)" >&2
        return 1
    fi
    _pyvenv_write_envrc "$name" "$force"
}

# A venv is not relocatable by plain `mv`: pyvenv.cfg, bin/activate* and every
# console-script shebang under bin/ bake in its absolute path. Moving one is
# therefore mv + rewriting that path in exactly those (plain-text) files, then
# dropping __pycache__ (bytecode records source paths, which tracebacks and
# debuggers show). Editable installs (.pth files) point at the SOURCE tree,
# which does not move, so they are left alone. (Same job as juggler's
# scripts/relocate-venv.sh.)
_pyvenv_mv() {  # OLD_DIR NEW_DIR   (NEW_DIR must not exist)
    local old new
    old="$(cd "$1" 2>/dev/null && pwd -P)" || { echo "pyvenv: no such directory: $1" >&2; return 1; }
    new="$2"
    [ -f "$old/pyvenv.cfg" ] || { echo "pyvenv: $old is not a venv (no pyvenv.cfg)" >&2; return 1; }
    [ -e "$new" ] && { echo "pyvenv: $new already exists" >&2; return 1; }
    # One made on another box / python will not run: nothing to relocate, recreate it.
    if ! "$old/bin/python" -c 'import sys' 2>/dev/null; then
        echo "pyvenv: $old/bin/python does not run; rm -rf it and pyvenv-create instead" >&2
        return 1
    fi

    # Every path the venv has baked in: where it is now, plus whatever
    # bin/activate says (differs if it was copied around or made via a symlink).
    local paths=()
    mapfile -t paths < <({ printf '%s\n' "$old"
                           grep -E '^[[:space:]]*(export )?VIRTUAL_ENV=' "$old/bin/activate" 2>/dev/null \
                               | grep -oE "/[^\"' )]+"; } | sort -u)

    mkdir -p "$(dirname "$new")" || return 1
    echo "pyvenv: mv $old -> $new"
    mv "$old" "$new" || return 1

    # Rewrite each path where it ends (followed by /, a closing quote/paren,
    # or end of line) -- never as a prefix of some longer path.
    local p pat rep files=() n=0
    rep="$(_pyvenv_sed_rep "$new")"
    for p in "${paths[@]}"; do
        mapfile -t files < <(grep -rIlF -- "$p" "$new/bin" "$new/pyvenv.cfg" 2>/dev/null)
        (( ${#files[@]} )) || continue
        pat="$(_pyvenv_sed_pat "$p")"
        sed -i -e "s|${pat}\([/\"' )]\)|${rep}\1|g" -e "s|${pat}\$|${rep}|" "${files[@]}"
        n=$(( n + ${#files[@]} ))
    done
    # The "(name) " prompt label venv bakes into bin/activate* (cosmetic; PS1
    # shows basename $VIRTUAL_ENV): keep it equal to the directory name.
    local ob nb
    ob="$(basename "$old")"; nb="$(basename "$new")"
    if [ "$ob" != "$nb" ]; then
        sed -i "s|($(_pyvenv_sed_pat "$ob")) |($(_pyvenv_sed_rep "$nb")) |g" "$new"/bin/activate* 2>/dev/null
    fi
    find "$new" -type d -name __pycache__ -prune -exec rm -rf {} + 2>/dev/null

    # Verify: the interpreter and `source bin/activate` both agree on the new home.
    local prefix got
    prefix="$("$new/bin/python" -c 'import sys; print(sys.prefix)' 2>&1)"
    got="$(bash -c "source '$new/bin/activate' && printf '%s' \"\$VIRTUAL_ENV\"" 2>&1)"
    if [ "$prefix" != "$new" ] || [ "$got" != "$new" ]; then
        echo "pyvenv: VERIFY FAILED after move: sys.prefix='$prefix', activate gives '$got', want '$new'" >&2
        return 1
    fi
    echo "pyvenv: rewrote ${paths[*]} in $n files; ok ($("$new/bin/python" --version 2>&1))"
}

pyvenv-adopt() {
    local usage='usage: pyvenv-adopt [-f] [NAME] [VENV_DIR]'
    local force=0 OPTIND opt
    while getopts ':fh' opt; do
        case "$opt" in
            f) force=1;;
            h) echo "$usage"; return 0;;
            *) echo "$usage" >&2; return 2;;
        esac
    done
    shift $((OPTIND - 1))
    local name="$1" src="$2"

    # No VENV_DIR: the one */pyvenv.cfg directly under the cwd.
    if [ -z "$src" ]; then
        local found=() f
        for f in ./*/pyvenv.cfg ./.[!.]*/pyvenv.cfg; do
            [ -f "$f" ] && found+=("${f%/pyvenv.cfg}")
        done
        case ${#found[@]} in
            0) echo "pyvenv-adopt: no venv (*/pyvenv.cfg) under $PWD; pass VENV_DIR" >&2; return 1;;
            1) src="${found[0]}";;
            *) echo "pyvenv-adopt: more than one venv here (${found[*]}); pass VENV_DIR" >&2; return 1;;
        esac
    fi
    [ -f "$src/pyvenv.cfg" ] || { echo "pyvenv-adopt: $src is not a venv (no pyvenv.cfg)" >&2; return 1; }

    local old ver
    old="$(cd "$src" && pwd -P)" || return 1
    # Does it even run? (One made on another box / python will not -- recreate those.)
    if ! "$old/bin/python" -c 'import sys' 2>/dev/null; then
        echo "pyvenv-adopt: $old/bin/python does not run; rm -rf it and pyvenv-create instead" >&2
        return 1
    fi
    ver="$(_pyvenv_pyver "$old/bin/python")" || return 1
    name="${name:-$(_pyvenv_default_name "$ver")}"
    _pyvenv_check_name "$name" || return 1

    local new="$PY_VENVS/$name"
    [ -e "$new" ] && { echo "pyvenv-adopt: $new already exists" >&2; return 1; }
    if [ "$force" != 1 ] && ! _pyvenv_envrc_replaceable; then
        echo "pyvenv-adopt: $PWD/.envrc has more than venv activation in it; re-run with -f" >&2
        return 1
    fi

    _pyvenv_mv "$old" "$new" || return 1
    if [ "$VIRTUAL_ENV" = "$old" ]; then
        echo "pyvenv-adopt: note: this shell still has the old path active; direnv reloads at the next prompt" >&2
    fi
    _pyvenv_write_envrc "$name" 1
}

pyvenv-ls() {
    [ -d "$PY_VENVS" ] || { echo "pyvenv-ls: $PY_VENVS does not exist" >&2; return 1; }
    local d v state
    for d in "$PY_VENVS"/*/; do
        d="${d%/}"
        [ -f "$d/pyvenv.cfg" ] || continue
        v="$(sed -n 's/^version *= *//p' "$d/pyvenv.cfg")"
        state=''
        "$d/bin/python" -c 'import sys' 2>/dev/null || state='BROKEN (python does not run)'
        printf '%s\t%s\t%s\n' "$(basename "$d")" "${v:-?}" "$state"
    done | column -t -s $'\t'
}

# Tab-complete venv names for pyvenv-use.
_pyvenv_complete_names() {
    local cur="${COMP_WORDS[COMP_CWORD]}"
    COMPREPLY=()
    [ -d "$PY_VENVS" ] || return 0
    mapfile -t COMPREPLY < <(cd "$PY_VENVS" && compgen -d -- "$cur")
}
complete -F _pyvenv_complete_names pyvenv-use
